name: inksy
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animations: 1.0.0+5

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets: 
    - assets/fonts/Avenir-Next-Regular.svg
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/Avenir-Next-Regular.ttf
    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik-Bold.ttf